import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Priora.AI',
  description: 'Terms of service for Priora.AI AI-powered patent prior art search.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0f1e] flex flex-col">
      <nav className="border-b border-[#1e293b] px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-sm">P</span>
            </div>
            <span className="font-bold text-xl text-white tracking-tight">Priora.AI</span>
          </Link>
          <Link href="/" className="text-sm text-slate-400 hover:text-white transition-colors">
            ← Back
          </Link>
        </div>
      </nav>

      <main className="flex-1 px-6 py-16">
        <article className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-slate-500 text-sm mb-10">Last updated: May 2026</p>

          <div className="space-y-8 text-slate-300 text-sm leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing and using Priora.AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
              <p>Priora.AI is an AI-powered prior art search tool that searches across multiple patent and academic databases and generates automated patentability reports. The Service is provided as an internal research aid for inventors, patent attorneys, and IP professionals.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">3. Not Legal Advice</h2>
              <p className="mb-3">
                <strong className="text-amber-400">Important:</strong> The reports and analyses generated by Priora.AI do <strong className="text-slate-100">not</strong> constitute legal advice, formal patentability opinions, freedom-to-operate analyses, or patent prosecution guidance.
              </p>
              <ul className="list-disc list-outside pl-5 space-y-1.5">
                <li>AI-generated reports may contain errors, miss relevant prior art, or misclassify references.</li>
                <li>You must consult a qualified, registered patent attorney or agent before making any filing, licensing, investment, or commercialization decisions.</li>
                <li>Priora.AI is not a law firm and does not provide legal representation.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">4. User Accounts</h2>
              <ul className="list-disc list-outside pl-5 space-y-1.5">
                <li>You must create an account through our authentication provider (Clerk) to use the Service.</li>
                <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
                <li>You agree to provide accurate information and to not create accounts for fraudulent purposes.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">5. Usage Limits</h2>
              <p className="mb-3">Free tier users are limited to 3 searches per day. Usage limits may be adjusted at our discretion. Abuse of the service (including automated scraping, bot access, or circumventing rate limits) may result in account suspension.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">6. Intellectual Property</h2>
              <ul className="list-disc list-outside pl-5 space-y-1.5">
                <li><strong className="text-slate-100">Your Content:</strong> You retain ownership of all invention descriptions you submit. By using the Service, you grant Priora.AI a limited license to process your descriptions for the purpose of generating search results and reports.</li>
                <li><strong className="text-slate-100">Generated Reports:</strong> Reports generated by the Service are provided for your use. You may download, share, and use them as you see fit.</li>
                <li><strong className="text-slate-100">Service IP:</strong> The Priora.AI platform, algorithms, and branding are the intellectual property of Priora.AI.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
              <p className="mb-3">To the maximum extent permitted by applicable law:</p>
              <ul className="list-disc list-outside pl-5 space-y-1.5">
                <li>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied.</li>
                <li>We do not warrant that searches will find all relevant prior art or that reports will be accurate or complete.</li>
                <li>Priora.AI shall not be liable for any damages arising from reliance on AI-generated reports, including but not limited to patent rejections, financial losses, or missed prior art.</li>
                <li>Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">8. Prohibited Use</h2>
              <ul className="list-disc list-outside pl-5 space-y-1.5">
                <li>Using the Service for any unlawful purpose.</li>
                <li>Submitting content that infringes on third-party intellectual property rights.</li>
                <li>Attempting to reverse-engineer, decompile, or extract source code from the Service.</li>
                <li>Automated access or scraping of the Service beyond normal usage.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">9. Termination</h2>
              <p>We may suspend or terminate your access to the Service at any time, with or without cause. Upon termination, your right to use the Service ceases immediately. You may request export of your data prior to termination.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">10. Changes to Terms</h2>
              <p>We reserve the right to modify these Terms at any time. Material changes will be communicated via the Service or email. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-white mb-3">11. Contact</h2>
              <p>
                For questions about these Terms, contact us at{' '}
                <a href="mailto:mugilvannan@myipstrategy.com" className="text-blue-400 hover:text-blue-300 underline underline-offset-2">
                  mugilvannan@myipstrategy.com
                </a>.
              </p>
            </section>
          </div>
        </article>
      </main>

      <footer className="border-t border-[#1e293b] px-6 py-6 text-center text-slate-500 text-sm">
        © {new Date().getFullYear()} Priora.AI — All rights reserved
      </footer>
    </div>
  );
}
